# Generated by Django 3.2.7 on 2021-09-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieid', models.AutoField(primary_key=True, serialize=False)),
                ('tmdb_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=128)),
                ('genre', models.JSONField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=128, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=128, null=True)),
                ('production_countries', models.JSONField(blank=True, null=True)),
                ('runtime', models.PositiveIntegerField(blank=True, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.PositiveIntegerField(blank=True, null=True)),
                ('cast', models.JSONField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movieti',
            fields=[
                ('movieti', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('character', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('imgurl', models.CharField(blank=True, max_length=1024, null=True)),
                ('content1', models.TextField(blank=True, null=True)),
                ('content2', models.TextField(blank=True, null=True)),
                ('content3', models.TextField(blank=True, null=True)),
                ('content4', models.TextField(blank=True, null=True)),
                ('content5', models.TextField(blank=True, null=True)),
                ('movielist', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movieti',
            },
        ),
    ]
