# Generated by Django 3.2.7 on 2021-09-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentid', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keywordid', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'keyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieid', models.AutoField(primary_key=True, serialize=False)),
                ('tmdb_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=128)),
                ('genre', models.TextField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=128, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=128, null=True)),
                ('production_countries', models.TextField(blank=True, null=True)),
                ('runtime', models.PositiveIntegerField(blank=True, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.PositiveIntegerField(blank=True, null=True)),
                ('cast', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('ratingid', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recommendationmovie',
            fields=[
                ('recommendid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'recommendationmovie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('scrapid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'scrap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('nickname', models.CharField(max_length=128)),
                ('profileimg', models.CharField(blank=True, max_length=128, null=True)),
                ('like_country', models.CharField(blank=True, max_length=128, null=True)),
                ('movieti', models.CharField(blank=True, max_length=4, null=True)),
                ('like_genre', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usermovielike',
            fields=[
                ('likeid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usermovielike',
                'managed': False,
            },
        ),
    ]
