# Generated by Django 3.2.7 on 2021-09-23 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210923_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recommendationmovie',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scrap',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usermovielike',
            options={},
        ),
    ]
