version: "3"
services:
    nginx:
        image: nginx:1.17.10
        container_name: ng01
        ports:
            - "80:80"
        volumes:
            - ./BackEnd:/BackEnd
            - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - web

    web:
        build: .
        container_name: leadme_01
        command: bash -c "
            python3 manage.py collectstatic --no-input &&
            python3 manage.py makemigrations && 
            python3 manage.py migrate && 
            gunicorn project.dev.wsgi:application -b 0:80"
        depends_on:
            - db
        volumes:
            - ./BackEnd:/BackEnd

    db:
        image: mysql
        container_name: mysql_leadme
        environment:
            MYSQL_DATABASE: bigdatapjt
            MYSQL_USER: jiahn
            MYSQL_PASSWORD: jiahn1234  # MYSQL 패스워드 설정 옵션
            TZ: Asia/Seoul